### ISSUE TITLE
Upstream the repo

### ISSUE THREAD

**Issue by bprashanth** [aledbf/kube-haproxy-router#1]
chauncey posted this on the kubernetes irc channel and I decided to reach out, because I don't want it to be hard to maintain spin-off kubernetes components down the line. This is just my 2c. 

Now that the kubernetes pr referenced in the README is in (11679:  https://github.com/kubernetes/contrib/tree/master/service-loadbalancer) it would be great if you could upstream this repo into /contrib. I'm willing to help clarify/take patches to support things that might not work right away. I think it will be worth your time because we're currently fleshing out the L7 api, and when that's in, we'll just lift and shift the service loadbalancer so your proxy should continue to work.

Doing the work now when the 2 aren't very different is bound to be much easier than a month down the line when the service-loadbalancer has been moved, and the api revved.

**Comment by aledbf** [comment]
@bprashanth I would love to upstream the changes present in this repository. Any help/advice you can give me on how to do this is welcomed.

_This are some of the changes I have made:_
- routing using the Host header instead a path
- ~~add a default backend for those request that do not match a haproxy rule (returning a default page)~~
- ~~[proc.StartReaper()](github.com/openshift/origin/pkg/util/proc) to remove haproxy zombie processes as a result from the reload.~~
- ~~local syslog server with the objective to receive the haproxy logs and redirect that to stdout (is not possible to use a file or device)~~
- use of label content=json to change the error files to be used (I have a mix of apps and rest json services)
- ~~alpine instead of ubuntu as base image:~~

```
gcr.io/google_containers/servicelb      0.1     5fccf997c07f        3 weeks ago         201.8 MB
aledbf/kube-haproxy-router              v0.0.1  13bcd9b15c03        5 weeks ago         22.25 MB
```

I don't know if something of this is interesting. Please let me know.

**Comment by bprashanth** [comment]
@aledbf this is great. I looked through some of the commits and it looks like it'll just work with upstream. If you have the time just submit prs and I'll do review. 

If you want advice on how to proceed about something specific, I'm beeps on slack (kubernetes.slack.com, kubernetes-dev/users) and irc (#google-containers). 

To be clear, currently the service-loadbalancer has this scary disclaimer (https://github.com/kubernetes/contrib/blob/master/service-loadbalancer/README.md#disclaimer) because, like it says, I have never deployed haproxy to prod. I think all the features you mentioned take it closer to being production ready.
